CREATE DATABASE VENTAS
GO

USE VENTAS
GO

CREATE SCHEMA PERSONA
GO

CREATE SCHEMA EQUIPO
GO

CREATE SCHEMA VENTA
GO


CREATE TABLE PERSONA.PERSONA
(
	CODPER INT IDENTITY(1,1),
	NOMPER VARCHAR(60),
	APEPER VARCHAR(60),	
	DNIPER CHAR(8),
	TIPOPER CHAR(1),
	CODSUC INT,
	DIRPER VARCHAR(60),
	CELPER CHAR(9),
	SEXPER CHAR(1),
	ESTPER CHAR(1)
	CONSTRAINT CODPER_PK PRIMARY KEY(CODPER)
)
GO

CREATE TABLE PERSONA.SUCURSAL
(
	CODSUC INT IDENTITY(1,1),
	NOMSUC VARCHAR(60),
	DIRSUC VARCHAR(60),
	ESTSUC CHAR(1)
	CONSTRAINT CODSUC_PK PRIMARY KEY(CODSUC)
)
GO

CREATE TABLE EQUIPO.EQUIPO
(
	CODEQUI INT IDENTITY(1,1),
	NOMEQUI VARCHAR(60),
	CATEQUI VARCHAR(60),
	PRECEQUI DECIMAL(5,1),
	CANTEQUI INT,
	ESTEQUI CHAR(1)
	CONSTRAINT CODEQUI PRIMARY KEY(CODEQUI)
)
GO

CREATE TABLE VENTA.VENTA
(
	CODVENT INT IDENTITY(1,1),
	CODVEND INT,
	CODCLI INT,
	FECHVENT DATE DEFAULT GETDATE(),
	ESTVENT CHAR(1)
	CONSTRAINT CODVENT_PK PRIMARY KEY(CODVENT)
)
GO

CREATE TABLE VENTA.VENTA_DETALLE
(
	CODVENTD INT IDENTITY(1,1),
	CODVENT INT,
	CODEQUI INT,
	CANTVENTD INT,
	ESTVENTD CHAR(1)
	CONSTRAINT CODVENTD_PK PRIMARY KEY(CODVENTD)
)
GO

ALTER TABLE PERSONA.PERSONA
	ADD CONSTRAINT CODSUC_FK FOREIGN KEY(CODSUC)
	REFERENCES PERSONA.SUCURSAL(CODSUC)
GO

ALTER TABLE VENTA.VENTA
	ADD CONSTRAINT CODVEND_FK FOREIGN KEY(CODVEND)
	REFERENCES PERSONA.PERSONA(CODPER)
GO

ALTER TABLE VENTA.VENTA
	ADD CONSTRAINT CODCLI_FK FOREIGN KEY(CODCLI)
	REFERENCES PERSONA.PERSONA(CODPER)
GO

ALTER TABLE VENTA.VENTA_DETALLE
	ADD CONSTRAINT CODVENT_FK FOREIGN KEY(CODVENT)
	REFERENCES VENTA.VENTA(CODVENT)
GO

ALTER TABLE VENTA.VENTA_DETALLE
	ADD CONSTRAINT CODEQUI_FK FOREIGN KEY(CODEQUI)
	REFERENCES EQUIPO.EQUIPO(CODEQUI)
GO


INSERT INTO PERSONA.SUCURSAL (NOMSUC,DIRSUC)
	VALUES
	('Imperial','Av los mares')
GO

INSERT INTO PERSONA.PERSONA (NOMPER,APEPER,DNIPER,TIPOPER,CODSUC,DIRPER,CELPER,SEXPER)
	VALUES
	('Ciurlizza','Ascencio','73931447','A','1','Zuñiga','934936214','M')
GO


SELECT * FROM PERSONA.SUCURSAL
GO

SELECT * FROM PERSONA.PERSONA
GO