CREATE TABLE [EQUIPO].[EQUIPO]
(
[CODEQUI] [int] NOT NULL IDENTITY(1, 1),
[NOMEQUI] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[CATEQUI] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[PRECEQUI] [decimal] (5, 1) NULL,
[CANTEQUI] [int] NULL,
[ESTEQUI] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [EQUIPO].[EQUIPO] ADD CONSTRAINT [CODEQUI] PRIMARY KEY CLUSTERED  ([CODEQUI]) ON [PRIMARY]
GO
