CREATE TABLE [PERSONA].[SUCURSAL]
(
[CODSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[DIRSUC] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[ESTSUC] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[SUCURSAL] ADD CONSTRAINT [CODSUC_PK] PRIMARY KEY CLUSTERED  ([CODSUC]) ON [PRIMARY]
GO
