CREATE TABLE [PERSONA].[PERSONA]
(
[CODPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[APEPER] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[DNIPER] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[TIPOPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[CODSUC] [int] NULL,
[DIRPER] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[CELPER] [char] (9) COLLATE Modern_Spanish_CI_AS NULL,
[SEXPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [CODPER_PK] PRIMARY KEY CLUSTERED  ([CODPER]) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [CODSUC_FK] FOREIGN KEY ([CODSUC]) REFERENCES [PERSONA].[SUCURSAL] ([CODSUC])
GO
