CREATE TABLE [VENTA].[VENTA_DETALLE]
(
[CODVENTD] [int] NOT NULL IDENTITY(1, 1),
[CODVENT] [int] NULL,
[CODEQUI] [int] NULL,
[CANTVENTD] [int] NULL,
[ESTVENTD] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [CODVENTD_PK] PRIMARY KEY CLUSTERED  ([CODVENTD]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [CODEQUI_FK] FOREIGN KEY ([CODEQUI]) REFERENCES [EQUIPO].[EQUIPO] ([CODEQUI])
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [CODVENT_FK] FOREIGN KEY ([CODVENT]) REFERENCES [VENTA].[VENTA] ([CODVENT])
GO
