CREATE TABLE [VENTA].[VENTA]
(
[CODVENT] [int] NOT NULL IDENTITY(1, 1),
[CODVEND] [int] NULL,
[CODCLI] [int] NULL,
[FECHVENT] [date] NULL CONSTRAINT [DF__VENTA__FECHVENT__3D5E1FD2] DEFAULT (getdate()),
[ESTVENT] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [CODVENT_PK] PRIMARY KEY CLUSTERED  ([CODVENT]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [CODCLI_FK] FOREIGN KEY ([CODCLI]) REFERENCES [PERSONA].[PERSONA] ([CODPER])
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [CODVEND_FK] FOREIGN KEY ([CODVEND]) REFERENCES [PERSONA].[PERSONA] ([CODPER])
GO
